### ISSUE TITLE
Build fails immediately due to git changes

### ISSUE THREAD

**Issue by WolfJMZ** [mitchcapper/CefSharpDockerfiles#15]
Hey there!

I tried running build.ps1 and it instantly failed after setting up the container with an error about uncommitted git changes in the tools repo.

I can't get a log atm since I'm out and busy but I'll try to grab it later.

Building locally on windows 11.

Thanks,
Jammerxd

**Comment by mitchcapper** [comment]
I am currently working to try and get CI setup so it can autobuild.  Largest problem right now is the source checkout step takes so many hours I can't complete it and compress it within the 6 hour time limit.   I will commit some of the other changes up in the next week or so to make it work with the latest (at least tested on 105).

**Comment by WolfJMZ** [comment]
If you need a dedicated build server I might be able to provide a VM on my dedicated server. Discord is WolfJMZ#2534.

**Comment by WolfJMZ** [comment]
The other thing is - instead of checking out code via git have you considered downloading a zip or tarball instead?

**Comment by WolfJMZ** [comment]
```
Generating CEF project files...
Creating C:\code\chromium_git\chromium\src\out\Debug_GN_x64 directory.
Traceback (most recent call last):
  File "C:/code/chromium_git/chromium/src/build/toolchain/win/setup_toolchain.py", line 319, in <module>
    main()
  File "C:/code/chromium_git/chromium/src/build/toolchain/win/setup_toolchain.py", line 277, in main
    env = _LoadToolchainEnv(cpu, toolchain_root, win_sdk_path, target_store)
  File "C:/code/chromium_git/chromium/src/build/toolchain/win/setup_toolchain.py", line 193, in _LoadToolchainEnv
    return _ExtractImportantEnvironment(variables)
  File "C:/code/chromium_git/chromium/src/build/toolchain/win/setup_toolchain.py", line 67, in _ExtractImportantEnvironment
    raise Exception(
Exception: Path "C:\Program Files (x86)\Windows Kits\10\include\10.0.20348.0\shared" from environment variable "include" does not exist. Make sure the necessary SDK is installed.
ERROR at //build/toolchain/win/toolchain.gni:500:24: Script returned non-zero exit code.
  win_toolchain_data = exec_script("//build/toolchain/win/setup_toolchain.py",
                       ^----------
Current dir: C:/code/chromium_git/chromium/src/out/Debug_GN_x64/
Command: c:/code/depot_tools/bootstrap-2@3_8_10_chromium_23_bin/python3/bin/python3.exe C:/code/chromium_git/chromium/src/build/toolchain/win/setup_toolchain.py "C:\Program Files (x86)/Microsoft Visual Studio/2019/Community" "C:\Program Files (x86)\Windows Kits\10" "C:\Windows\System32;C:\Windows\SysWOW64;Arm64Unused" win x86 environment.x86
Returned 1.
See //build/toolchain/win/BUILD.gn:34:3: whence it was called.
  win_toolchains("x86") {
  ^----------------------
See //BUILD.gn:77:1: which caused the file to be included.
group("gn_all") {
^----------------
Traceback (most recent call last):
  File "tools\gclient_hook.py", line 146, in <module>
    RunAction(src_dir, cmd)
  File "C:\code\chromium_git\chromium\src\cef\tools\gclient_util.py", line 36, in RunAction
    command, cwd=dir, always_show_header=True, print_stdout=True)
  File "c:/code/depot_tools/gclient_utils.py", line 716, in CheckCallAndFilter
    rv, args, kwargs.get('cwd', None), command_output.getvalue(), None)
subprocess2.CalledProcessError: Command 'gn gen out\\Debug_GN_x64 --ide=vs2019 --sln=cef --filters=//cef/*' returned non-zero exit status 1 in C:\code\chromium_git\chromium\src
Traceback (most recent call last):
  File "C:/code/chromium_git/chromium/src/build/toolchain/win/setup_toolchain.py", line 319, in <module>
    main()
  File "C:/code/chromium_git/chromium/src/build/toolchain/win/setup_toolchain.py", line 277, in main
    env = _LoadToolchainEnv(cpu, toolchain_root, win_sdk_path, target_store)
  File "C:/code/chromium_git/chromium/src/build/toolchain/win/setup_toolchain.py", line 193, in _LoadToolchainEnv
    return _ExtractImportantEnvironment(variables)
  File "C:/code/chromium_git/chromium/src/build/toolchain/win/setup_toolchain.py", line 67, in _ExtractImportantEnvironment
    raise Exception(
Exception: Path "C:\Program Files (x86)\Windows Kits\10\include\10.0.20348.0\shared" from environment variable "include" does not exist. Make sure the necessary SDK is installed.
ERROR at //build/toolchain/win/toolchain.gni:500:24: Script returned non-zero exit code.
  win_toolchain_data = exec_script("//build/toolchain/win/setup_toolchain.py",
                       ^----------
Current dir: C:/code/chromium_git/chromium/src/out/Debug_GN_x64/
Command: c:/code/depot_tools/bootstrap-2@3_8_10_chromium_23_bin/python3/bin/python3.exe C:/code/chromium_git/chromium/src/build/toolchain/win/setup_toolchain.py "C:\Program Files (x86)/Microsoft Visual Studio/2019/Community" "C:\Program Files (x86)\Windows Kits\10" "C:\Windows\System32;C:\Windows\SysWOW64;Arm64Unused" win x86 environment.x86
Returned 1.
See //build/toolchain/win/BUILD.gn:34:3: whence it was called.
  win_toolchains("x86") {
  ^----------------------
See //BUILD.gn:77:1: which caused the file to be included.
group("gn_all") {
^----------------
```

Here's a log of the error that I'm stuck at.

**Comment by WolfJMZ** [comment]
There's a number of other problems - in Visual Studio 2022, the ref folder got moved to the obj folder, not the bin folder so the nuspec and nuget target files also have to be updated respectively, but the actual compile is easy for CEF itself.
