### ISSUE TITLE
error: pathspec 'origin/3370' did not match any file(s) known to git

### ISSUE THREAD

**Issue by maxhora** [mitchcapper/CefSharpDockerfiles#5]
Thank you for sharing amazing build scripts!

It seems that `3370` branch is not found in Chromium repo for some reasons.

```
PS C:\build-cefsharp>> .\build.ps1
Warning when running this build command in a remote powershell session you will not see realtime output generated by commands run.  This is due to a limitation in remote powershell.  You can work around this by running the build.ps1 using remote desktop instead.  In general it is only helpful to see the output if there is an error.  The stdout and stderr will be captured and printed for remote sessions but only after a command finishes.

Confirm
Warning linking may take around 27 during linking.  Your machine may not have enough memory, make sure your page files
are working and can grow to allow it. (Disable this warning with -NoMemoryWarn flag). Do you want to proceed?
[Y] Yes  [N] No  [S] Suspend  [?] Help (default is "Y"):
11/25/2019 00:54:02 Starting took 2.6 secs
Running: docker pull mcr.microsoft.com/windows/servercore:1809-amd64 in C:\build-cefsharp
1809-amd64: Pulling from windows/servercore
Digest: sha256:64385c3c59e4c85862306505d486467d2e150174f21be373d5aab4c616a1dc72
Status: Image is up to date for mcr.microsoft.com/windows/servercore:1809-amd64
mcr.microsoft.com/windows/servercore:1809-amd64
11/25/2019 00:54:03 Pull base file took 0.4 secs
Running: docker build --memory=30g --build-arg BASE_DOCKER_FILE="mcr.microsoft.com/windows/servercore:1809-amd64" -f Dockerfile_vs -t vs . in C:\build-cefsharp
Sending build context to Docker daemon  112.6kB
Step 1/14 : FROM mcr.microsoft.com/windows/servercore:1809-amd64
 ---> 733821d00bd5
Step 2/14 : SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
 ---> Running in 9b4f1e1bfe0d
Removing intermediate container 9b4f1e1bfe0d
Step 3/14 : RUN mkdir c:\code\automate;mkdir c:\temp\;mkdir c:\code\depot_tools;
 ---> cf34ff90bc40
 ---> Running in f9a3fa441ac7
    Directory: C:\code
Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       11/25/2019  12:54 AM                automate
    Directory: C:\
Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       11/25/2019  12:54 AM                temp
    Directory: C:\code
Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       11/25/2019  12:54 AM                depot_tools
Removing intermediate container f9a3fa441ac7
 ---> 2e9ff028d856
Step 4/14 : RUN Invoke-WebRequest 'https://aka.ms/vscollect.exe' -OutFile 'C:\TEMP\collect.exe';
 ---> Running in b3955bdeaafc
Removing intermediate container b3955bdeaafc
Step 5/14 : RUN Invoke-WebRequest 'https://dist.nuget.org/win-x86-commandline/v4.1.0/nuget.exe' -OutFile 'c:\code\depot_tools\;';
 ---> fde527a8c809
 ---> Running in f438273d5d4c
Removing intermediate container f438273d5d4c
 ---> cf4f80481d85
Step 6/14 : RUN Invoke-WebRequest 'https://www.7-zip.org/a/7z1801-x64.msi' -OutFile '/code/7zip.msi';
 ---> Running in 1dc4b4f81415
Removing intermediate container 1dc4b4f81415
 ---> c3ad3b125893
Step 7/14 : RUN Start-Process msiexec.exe -Wait -ArgumentList '/i c:\code\7zip.msi /quiet /norestart /L*v install.log'
 ---> Running in d68335f4522e
Removing intermediate container d68335f4522e
 ---> 4d03751f4969
Step 8/14 : WORKDIR "Program Files"
 ---> Running in f4ab8ad270b4
Removing intermediate container f4ab8ad270b4
 ---> 3ca3727297d3
Step 9/14 : RUN Remove-Item -Recurse -Force '.\WindowsPowerShell\Modules\PSReadLine'
 ---> Running in fc5d016f340f
Removing intermediate container fc5d016f340f
 ---> 970c834054f4
Step 10/14 : WORKDIR c:\\code\\depot_tools
 ---> Running in 693d873c9a14
Removing intermediate container 693d873c9a14
Step 11/14 : RUN Invoke-WebRequest https://go.microsoft.com/fwlink/?linkid=864422 -OutFile 'C:\code\winsdksetup.exe';
 ---> 6ba30aa3b619
 ---> Running in 4aea5ee8cdc1
Removing intermediate container 4aea5ee8cdc1
 ---> 31e7a0ddd04d
Step 12/14 : RUN $p = Start-Process -Wait -PassThru -FilePath C:\code\winsdksetup.exe -ArgumentList ' /features OptionId.WindowsDesktopDebuggers /quiet /Log #"%TEMP%\\winsdksetup.log /norestart'; if (($ret = $p.ExitCode) -and ($ret -ne 3010)) { throw ('Install failed with exit code 0x{0:x}' -f $ret) }
 ---> Running in 1a2f0b47f616
Removing intermediate container 1a2f0b47f616
 ---> 870258838507
Step 13/14 : RUN Invoke-WebRequest 'https://aka.ms/vs/15/release/vs_community.exe' -OutFile 'C:\code\vs_community.exe';
 ---> Running in c470434bea09
Removing intermediate container c470434bea09
 ---> 826e4564b6c9
Step 14/14 : RUN $p = Start-Process -Wait -PassThru -FilePath C:\code\vs_community.exe -ArgumentList ' --quiet --wait --norestart --nocache --add Microsoft.Net.Component.4.7.1.SDK --add Microsoft.VisualStudio.Component.Windows10SDK --add Microsoft.Net.Component.4.6.1.SDK --add Microsoft.VisualStudio.ComponentGroup.NativeDesktop.Win81 --add Microsoft.VisualStudio.Component.Windows81SDK --add Microsoft.Net.Component.4.5.2.TargetingPack --add Microsoft.Net.Component.4.6.2.TargetingPack --add Microsoft.Net.Component.4.6.2.SDK --add Microsoft.VisualStudio.Component.Windows10SDK.16299.Desktop --add Microsoft.VisualStudio.Component.Windows10SDK.17134 --add Microsoft.VisualStudio.Component.Git --add Microsoft.VisualStudio.Component.Windows10SDK.15063.Desktop --add Microsoft.VisualStudio.Workload.NativeDesktop --add Microsoft.VisualStudio.Component.VC.ATLMFC --includeRecommended --remove Microsoft.VisualStudio.Component.Windows10SDK.10240 --remove Microsoft.VisualStudio.Component.Windows10SDK.10586 --remove Component.Android.NDK.R12B --remove Component.Android.SDK23.Private --remove Component.MDD.Android --remove Component.Unreal.Android --remove Component.Android.NDK.R15C --remove Component.Android.SDK19 --remove Component.Android.SDK22 --remove Component.Android.SDK23 --remove Component.Android.SDK25 --remove Component.MDD.Android --remove Component.Android.NDK.R12B --remove Component.Android.NDK.R12B_3264 --remove Component.Android.NDK.R13B --remove Component.Android.NDK.R13B_3264 --remove Component.Android.NDK.R15C_3264 --remove Component.Google.Android.Emulator.API23.V2 --remove Component.Android.SDK25 --remove Component.Google.Android.Emulator.API25 --remove Component.Android.SDK23.Private --remove Component.Google.Android.Emulator.API23.Private --remove Component.Android.Emulator --remove Component.Android.NDK.R11C --remove Component.Android.NDK.R11C_3264 --remove Microsoft.VisualStudio.Component.Windows10SDK.14393 --remove Microsoft.VisualStudio.Component.Phone.Emulator.15254 --remove Microsoft.VisualStudio.Component.Phone.Emulator.15254 --remove Microsoft.VisualStudio.Component.Phone.Emulator --remove Microsoft.VisualStudio.Component.Phone.Emulator.15063 --remove Component.Anaconda3.x64 --remove Component.Anaconda2.x64 --remove Component.Anaconda2.x86 --remove Component.Anaconda3.x86 --remove Microsoft.VisualStudio.Component.Unity --remove Component.UnityEngine.x64 --remove Component.UnityEngine.x86 --remove Component.Incredibuild --remove Component.IncredibuildMenu --remove Microsoft.VisualStudio.Component.Sharepoint.Tools --remove Microsoft.VisualStudio.Component.TeamOffice --remove Component.Cocos;'; if (($ret = $p.ExitCode) -and ($ret -ne 3010)) { C:\TEMP\collect.exe; throw ('Install failed with exit code 0x{0:x}' -f $ret) }; Remove-Item -Recurse -Force 'c:\ProgramData\Package Cache\'
 ---> Running in 95b4cc93748d
Removing intermediate container 95b4cc93748d
 ---> af3f761d5fba
[Warning] One or more build-args [BASE_DOCKER_FILE] were not consumed
Successfully built af3f761d5fba
Successfully tagged vs:latest
11/25/2019 02:06:42 VSBuild took 4359.4 secs
Running: docker build --memory=30g --build-arg CEF_SAVE_SOURCES="0" --build-arg BINARY_EXT="zip" --build-arg DUAL_BUILD="0" --build-arg GN_DEFINES="is_official_build=true proprietary_codecs=true ffmpeg_branding=Chrome" --build-arg GYP_DEFINES="" --build-arg CHROME_BRANCH="3370" -f Dockerfile_cef -t cef . in C:\build-cefsharp
Sending build context to Docker daemon  112.6kB
Step 1/19 : FROM vs
 ---> af3f761d5fba
Step 2/19 : RUN $env:Path = 'c:/Program Files/Git/bin/;' + $env:Path;setx /M PATH $env:Path;
 ---> Running in 2c04ec89a541
SUCCESS: Specified value was saved.
Removing intermediate container 2c04ec89a541
 ---> 71e64eb63111
Step 3/19 : RUN Invoke-WebRequest 'https://storage.googleapis.com/chrome-infra/depot_tools.zip' -OutFile 'C:/code/depot_tools.zip';
 ---> Running in 280ed7696bc4
Removing intermediate container 280ed7696bc4
 ---> 16510ac44f49
Step 4/19 : RUN Expand-Archive C:/code/depot_tools.zip -DestinationPath "C:/code/depot_tools";
 ---> Running in 4f11e096faf2
Removing intermediate container 4f11e096faf2
Step 5/19 : RUN $env:Path = 'c:/code/depot_tools/;' + $env:Path;setx /M PATH $env:Path;
 ---> 51795efa13ba
 ---> Running in 08db973d2bf1
SUCCESS: Specified value was saved.
Removing intermediate container 08db973d2bf1
 ---> 1d61c188b252
Step 6/19 : ARG GN_DEFINES="is_debug=false"
 ---> Running in 8a7fef0b240c
Removing intermediate container 8a7fef0b240c
 ---> 1175318789da
Step 7/19 : ENV DEPOT_TOOLS_WIN_TOOLCHAIN 0
 ---> Running in a09d6e4b86ae
Removing intermediate container a09d6e4b86ae
 ---> b37572a7e392
Step 8/19 : ENV CEF_USE_GN 1
 ---> Running in 2a793ba920ec
Removing intermediate container 2a793ba920ec
 ---> 4c5382f267e8
Step 9/19 : ENV GYP_MSVS_VERSION 2017
 ---> Running in a94aa7b48b0c
Removing intermediate container a94aa7b48b0c
 ---> 7082cc4cf373
Step 10/19 : ARG DUAL_BUILD="0"
 ---> Running in 2ac0e3acbdb3
Removing intermediate container 2ac0e3acbdb3
Step 11/19 : ARG BINARY_EXT="zip"
 ---> 34574d371b62
 ---> Running in f932612e4aa7
Removing intermediate container f932612e4aa7
 ---> c30741593b92
Step 12/19 : ARG GYP_DEFINES="target_arch=x64 "
 ---> Running in 51604223ec78
Removing intermediate container 51604223ec78
Step 13/19 : RUN setX /M DEPOT_TOOLS_WIN_TOOLCHAIN 0;setX /M GYP_MSVS_VERSION 2017;setx /M GN_DEFINES "$env:GN_DEFINES";setx /M GYP_DEFINES "$env:GYP_DEFINES";setx /M DUAL_BUILD "$env:DUAL_BUILD";
 ---> 6e532256920a
 ---> Running in 43e87bf24836
SUCCESS: Specified value was saved.
SUCCESS: Specified value was saved.
SUCCESS: Specified value was saved.
ERROR: Invalid syntax.
Type "SETX /?" for usage.

SUCCESS: Specified value was saved.
Removing intermediate container 43e87bf24836
 ---> a32174d8c52b
Step 14/19 : ARG CHROME_BRANCH=3239
 ---> Running in f9360fabec46
Removing intermediate container f9360fabec46
Step 15/19 : ADD https://bitbucket.org/chromiumembedded/cef/raw/master/tools/automate/automate-git.py c:/code/automate/
 ---> 5f64b605af01
 ---> f47f8116d782
Step 16/19 : RUN cd c:/code/depot_tools/;update_depot_tools.bat;git checkout .\cipd.ps1;update_depot_tools.bat;
 ---> Running in 19dbfb1ec85d
Downloading CIPD client for windows-amd64 from https://chrome-infra-packages.appspot.com/client?platform=windows-amd64&version=git_revision:2a121dde003a3079db0fdf58195b52cbf486f6ba...
Updated 0 paths from the index
Removing intermediate container 19dbfb1ec85d
 ---> a055f12c07d1
Step 17/19 : ADD functions.ps1 cef_build.ps1 cef_patch.ps1 cef_patch_*.diff c:/code/
 ---> caf1d892bdfb
Step 18/19 : ARG CEF_SAVE_SOURCES
 ---> Running in 20bf2fed4d0a
Removing intermediate container 20bf2fed4d0a
 ---> 7b72688c69bd
Step 19/19 : RUN c:/code/cef_build.ps1
 ---> Running in f9297a4554aa
Running: c:/code/depot_tools/python.bat c:/code/automate/automate-git.py --download-dir=c:/code --branch=3370 --no-build --no-debug-build --no-distrib in C:\code\depot_tools
Cloning into 'c:\code\cef'...
Checking out files:  72% (1333/1844)
Checking out files:  73% (1347/1844)
Checking out files:  74% (1365/1844)
Checking out files:  75% (1383/1844)
Checking out files:  76% (1402/1844)
Checking out files:  77% (1420/1844)
Checking out files:  78% (1439/1844)
Checking out files:  79% (1457/1844)
Checking out files:  80% (1476/1844)
Checking out files:  81% (1494/1844)
Checking out files:  82% (1513/1844)
Checking out files:  83% (1531/1844)
Checking out files:  84% (1549/1844)
Checking out files:  85% (1568/1844)
Checking out files:  86% (1586/1844)
Checking out files:  87% (1605/1844)
Checking out files:  88% (1623/1844)
Checking out files:  89% (1642/1844)
Checking out files:  90% (1660/1844)
Checking out files:  91% (1679/1844)
Checking out files:  92% (1697/1844)
Checking out files:  93% (1715/1844)
Checking out files:  94% (1734/1844)
Checking out files:  95% (1752/1844)
Checking out files:  96% (1771/1844)
Checking out files:  97% (1789/1844)
Checking out files:  98% (1808/1844)
Checking out files:  99% (1826/1844)
Checking out files: 100% (1844/1844)
Checking out files: 100% (1844/1844), done.
error: pathspec 'origin/3370' did not match any file(s) known to git
--> Depot Tools Directory: c:\code\depot_tools
-------- Running "update_depot_tools.bat" in "c:\code\depot_tools"...
--> Updating depot_tools
--> CEF URL: https://bitbucket.org/chromiumembedded/cef.git
--> Download Directory: c:\code
--> CEF Source Directory: c:\code\cef
-------- Running "c:\code\depot_tools\git.bat rev-parse HEAD" in "c:\code\cef"...
-------- Running "c:\code\depot_tools\git.bat clone https://bitbucket.org/chromiumembedded/cef.git c:\code\cef" in "c:\code"...
--> CEF Branch: 3370
-------- Running "c:\code\depot_tools\git.bat rev-parse origin/3370" in "c:\code\cef"...
-------- Running "c:\code\depot_tools\git.bat checkout origin/3370" in "c:\code\cef"...
--> CEF Current Checkout: f9706f260aa9fd78c799c1456f0ac75d13f5e7ba
--> CEF Desired Checkout: origin/3370 (origin/3370)
  File "c:/code/automate/automate-git.py", line 1274, in <module>
Traceback (most recent call last):
    cef_dir, depot_tools_dir)
    args, cwd=working_dir, env=env, shell=(sys.platform == 'win32'))
  File "c:/code/automate/automate-git.py", line 61, in run
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['c:\\code\\depot_tools\\git.bat', 'checkout', 'origin/3370']' returned non-zero exit status 1
  File "c:\code\depot_tools\bootstrap-3_8_0b1_chromium_1_bin\python\bin\lib\subprocess.py", line 186, in check_call
1
Set-Location : Cannot find path 'C:\code\chromium\src\cef' because it does not
exist.
At C:\code\cef_build.ps1:28 char:1
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ Set-Location -Path c:/code/chromium/src/cef;
   ) [Set-Location], ItemNotFoundException
    + CategoryInfo          : ObjectNotFound: (C:\code\chromium\src\cef:String
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.SetLo
   cationCommand


The command 'powershell -Command $ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue'; c:/code/cef_build.ps1' returned a non-zero code: 1
Caught an exception: Process docker build --memory=30g --build-arg CEF_SAVE_SOURCES="0" --build-arg BINARY_EXT="zip" --build-arg DUAL_BUILD="0" --build-arg GN_DEFINES="is_official_build=true proprietary_codecs=true ffmpeg_branding=Chrome" --build-arg GYP_DEFINES="" --build-arg CHROME_BRANCH="3370" -f Dockerfile_cef -t cef . exited with non zero code: 1 aborting!
        Exception Type: System.Management.Automation.RuntimeException
        Stack Trace: at RunProc, C:\build-cefsharp\functions.ps1: line 82
        at <ScriptBlock>, C:\build-cefsharp\build.ps1: line 70
        at <ScriptBlock>, <No file>: line 1
        at confirm, C:\build-cefsharp\functions.ps1: line 106
        at <ScriptBlock>, C:\build-cefsharp\build.ps1: line 43
        at <ScriptBlock>, <No file>: line 1
PS C:\build-cefsharp>>
```

**Comment by mitchcapper** [comment]
I do have some upcoming updates but I don't think that is your issue.  3370 isn't a cef build, you mean 3770 maybe?  Look at the branch listings at: https://bitbucket.org/chromiumembedded/cef/src/master/

**Comment by maxhora** [comment]
Got it, thanks,
I meant that `3370` change was introduced with last commit https://github.com/mitchcapper/CefSharpDockerfiles/commit/c67f9fe1ec66304e5fff2874d8d3a80156cf4e42#diff-dc08dfee97300694e6e4f0a307f82574R1
So far I've rolled back to `3396`, but build failed for me with:

```
-------- Running "gclient sync --with_branch_heads --disable-syntax-validation --jobs 16" in "c:\code\chromium"...
--> Removing directory c:\code\chromium\src\out
--> Copying directory c:\code\cef to c:\code\chromium\src\cef
--> Creating directory c:\code\chromium\src\out
--> Writing file: c:\code\chromium\src\out\cef.branch
0
Running: c:/code/chromium/src/cef/cef_create_projects.bat  in C:\code\chromium\src\cef
Generating CEF version header file...
  File "tools\gclient_hook.py", line 34, in <module>
Traceback (most recent call last):
    RunAction(cef_dir, cmd)
    gclient_utils.CheckCallAndFilterAndHeader(command, cwd=dir, always=True)
AttributeError: 'module' object has no attribute 'CheckCallAndFilterAndHeader'
  File "C:\code\chromium\src\cef\tools\gclient_util.py", line 39, in RunAction
1
Running: c:/code/depot_tools/ninja.exe  -C out/Release_GN_x64 cefclient in C:\code\chromium\src
ninja: fatal: chdir to 'out/Release_GN_x64' - No such file or directory
ninja: Entering directory `out/Release_GN_x64'
Running: c:/code/depot_tools/ninja.exe  -C out/Release_GN_x64 cefclient in C:\code\chromium\src
ninja: fatal: chdir to 'out/Release_GN_x64' - No such file or directory
ninja: Entering directory `out/Release_GN_x64'
Running: c:/code/depot_tools/ninja.exe  -C out/Release_GN_x64 cefclient in C:\code\chromium\src
ninja: fatal: chdir to 'out/Release_GN_x64' - No such file or directory
ninja: Entering directory `out/Release_GN_x64'
Running: c:/code/depot_tools/ninja.exe  -C out/Release_GN_x64 cefclient in C:\code\chromium\src
ninja: fatal: chdir to 'out/Release_GN_x64' - No such file or directory
ninja: Entering directory `out/Release_GN_x64'
Running: c:/code/depot_tools/ninja.exe  -C out/Release_GN_x64 cefclient in C:\code\chromium\src
ninja: fatal: chdir to 'out/Release_GN_x64' - No such file or directory
ninja: Entering directory `out/Release_GN_x64'
Running: c:/code/depot_tools/ninja.exe  -C out/Release_GN_x64 cefclient in C:\code\chromium\src
ninja: fatal: chdir to 'out/Release_GN_x64' - No such file or directory
ninja: Entering directory `out/Release_GN_x64'
Running: c:/code/depot_tools/ninja.exe  -C out/Release_GN_x64 cefclient in C:\code\chromium\src
ninja: fatal: chdir to 'out/Release_GN_x64' - No such file or directory
ninja: Entering directory `out/Release_GN_x64'
Running: c:/code/depot_tools/ninja.exe  -C out/Release_GN_x64 cefclient in C:\code\chromium\src
ninja: fatal: chdir to 'out/Release_GN_x64' - No such file or directory
ninja: Entering directory `out/Release_GN_x64'
Running: c:/code/depot_tools/ninja.exe  -C out/Release_GN_x64 cefclient in C:\code\chromium\src
ninja: fatal: chdir to 'out/Release_GN_x64' - No such file or directory
ninja: Entering directory `out/Release_GN_x64'
Running: c:/code/depot_tools/ninja.exe  -C out/Release_GN_x64 cefclient in C:\code\chromium\src
ninja: fatal: chdir to 'out/Release_GN_x64' - No such file or directory
ninja: Entering directory `out/Release_GN_x64'
Running: c:/code/depot_tools/ninja.exe  -C out/Release_GN_x64 cefclient in C:\code\chromium\src
ninja: fatal: chdir to 'out/Release_GN_x64' - No such file or directory
ninja: Entering directory `out/Release_GN_x64'
Running: c:/code/depot_tools/ninja.exe  -C out/Release_GN_x64 cefclient in C:\code\chromium\src
ninja: fatal: chdir to 'out/Release_GN_x64' - No such file or directory
ninja: Entering directory `out/Release_GN_x64'
Running: c:/code/depot_tools/ninja.exe  -C out/Release_GN_x64 cefclient in C:\code\chromium\src
ninja: fatal: chdir to 'out/Release_GN_x64' - No such file or directory
ninja: Entering directory `out/Release_GN_x64'
Running: c:/code/depot_tools/ninja.exe  -C out/Release_GN_x64 cefclient in C:\code\chromium\src
ninja: fatal: chdir to 'out/Release_GN_x64' - No such file or directory
ninja: Entering directory `out/Release_GN_x64'
Running: c:/code/depot_tools/ninja.exe  -C out/Release_GN_x64 cefclient in C:\code\chromium\src
ninja: fatal: chdir to 'out/Release_GN_x64' - No such file or directory
ninja: Entering directory `out/Release_GN_x64'
Running: c:/code/depot_tools/ninja.exe  -C out/Release_GN_x64 cefclient in C:\code\chromium\src
ninja: fatal: chdir to 'out/Release_GN_x64' - No such file or directory
ninja: Entering directory `out/Release_GN_x64'
Running: c:/code/depot_tools/ninja.exe  -C out/Release_GN_x64 cefclient in C:\code\chromium\src
ninja: fatal: chdir to 'out/Release_GN_x64' - No such file or directory
ninja: Entering directory `out/Release_GN_x64'
Running: c:/code/depot_tools/ninja.exe  -C out/Release_GN_x64 cefclient in C:\code\chromium\src
ninja: fatal: chdir to 'out/Release_GN_x64' - No such file or directory
ninja: Entering directory `out/Release_GN_x64'
Running: c:/code/depot_tools/ninja.exe  -C out/Release_GN_x64 cefclient in C:\code\chromium\src
ninja: fatal: chdir to 'out/Release_GN_x64' - No such file or directory
ninja: Entering directory `out/Release_GN_x64'
Running: c:/code/depot_tools/ninja.exe  -C out/Release_GN_x64 cefclient in C:\code\chromium\src
ninja: fatal: chdir to 'out/Release_GN_x64' - No such file or directory
ninja: Entering directory `out/Release_GN_x64'
Running: c:/code/depot_tools/ninja.exe  -C out/Release_GN_x64 cefclient in C:\code\chromium\src
ninja: fatal: chdir to 'out/Release_GN_x64' - No such file or directory
ninja: Entering directory `out/Release_GN_x64'
Running: c:/code/depot_tools/ninja.exe  -C out/Release_GN_x86 cefclient in C:\code\chromium\src
ninja: fatal: chdir to 'out/Release_GN_x86' - No such file or directory
ninja: Entering directory `out/Release_GN_x86'
Running: c:/code/depot_tools/ninja.exe  -C out/Release_GN_x86 cefclient in C:\code\chromium\src
ninja: fatal: chdir to 'out/Release_GN_x86' - No such file or directory
ninja: Entering directory `out/Release_GN_x86'
Running: c:/code/depot_tools/ninja.exe  -C out/Release_GN_x86 cefclient in C:\code\chromium\src
ninja: fatal: chdir to 'out/Release_GN_x86' - No such file or directory
ninja: Entering directory `out/Release_GN_x86'
Running: c:/code/depot_tools/ninja.exe  -C out/Release_GN_x86 cefclient in C:\code\chromium\src
ninja: fatal: chdir to 'out/Release_GN_x86' - No such file or directory
ninja: Entering directory `out/Release_GN_x86'
Running: c:/code/depot_tools/ninja.exe  -C out/Release_GN_x86 cefclient in C:\code\chromium\src
ninja: fatal: chdir to 'out/Release_GN_x86' - No such file or directory
ninja: Entering directory `out/Release_GN_x86'
Running: c:/code/depot_tools/ninja.exe  -C out/Release_GN_x86 cefclient in C:\code\chromium\src
ninja: Entering directory `out/Release_GN_x86'
ninja: fatal: chdir to 'out/Release_GN_x86' - No such file or directory
Running: c:/code/depot_tools/ninja.exe  -C out/Release_GN_x86 cefclient in C:\code\chromium\src
ninja: Entering directory `out/Release_GN_x86'
ninja: fatal: chdir to 'out/Release_GN_x86' - No such file or directory
Running: c:/code/depot_tools/ninja.exe  -C out/Release_GN_x86 cefclient in C:\code\chromium\src
ninja: fatal: chdir to 'out/Release_GN_x86' - No such file or directory
ninja: Entering directory `out/Release_GN_x86'
Running: c:/code/depot_tools/ninja.exe  -C out/Release_GN_x86 cefclient in C:\code\chromium\src
ninja: fatal: chdir to 'out/Release_GN_x86' - No such file or directory
ninja: Entering directory `out/Release_GN_x86'
Running: c:/code/depot_tools/ninja.exe  -C out/Release_GN_x86 cefclient in C:\code\chromium\src
ninja: Entering directory `out/Release_GN_x86'
ninja: fatal: chdir to 'out/Release_GN_x86' - No such file or directory
Running: c:/code/depot_tools/ninja.exe  -C out/Release_GN_x86 cefclient in C:\code\chromium\src
ninja: fatal: chdir to 'out/Release_GN_x86' - No such file or directory
ninja: Entering directory `out/Release_GN_x86'
Running: c:/code/depot_tools/ninja.exe  -C out/Release_GN_x86 cefclient in C:\code\chromium\src
ninja: fatal: chdir to 'out/Release_GN_x86' - No such file or directory
ninja: Entering directory `out/Release_GN_x86'
ninja: fatal: chdir to 'out/Release_GN_x86' - No such file or directory
Running: c:/code/depot_tools/ninja.exe  -C out/Release_GN_x86 cefclient in C:\code\chromium\src
ninja: fatal: chdir to 'out/Release_GN_x86' - No such file or directory
ninja: Entering directory `out/Release_GN_x86'
Running: c:/code/depot_tools/ninja.exe  -C out/Release_GN_x86 cefclient in C:\code\chromium\src
ninja: fatal: chdir to 'out/Release_GN_x86' - No such file or directory
ninja: Entering directory `out/Release_GN_x86'
Running: c:/code/depot_tools/ninja.exe  -C out/Release_GN_x86 cefclient in C:\code\chromium\src
ninja: fatal: chdir to 'out/Release_GN_x86' - No such file or directory
ninja: Entering directory `out/Release_GN_x86'
Running: c:/code/depot_tools/ninja.exe  -C out/Release_GN_x86 cefclient in C:\code\chromium\src
ninja: fatal: chdir to 'out/Release_GN_x86' - No such file or directory
ninja: Entering directory `out/Release_GN_x86'
Running: c:/code/depot_tools/ninja.exe  -C out/Release_GN_x86 cefclient in C:\code\chromium\src
ninja: fatal: chdir to 'out/Release_GN_x86' - No such file or directory
ninja: Entering directory `out/Release_GN_x86'
Running: c:/code/depot_tools/ninja.exe  -C out/Release_GN_x86 cefclient in C:\code\chromium\src
ninja: fatal: chdir to 'out/Release_GN_x86' - No such file or directory
ninja: Entering directory `out/Release_GN_x86'
Running: c:/code/depot_tools/ninja.exe  -C out/Release_GN_x86 cefclient in C:\code\chromium\src
ninja: fatal: chdir to 'out/Release_GN_x86' - No such file or directory
ninja: Entering directory `out/Release_GN_x86'
Running: c:/code/depot_tools/ninja.exe  -C out/Release_GN_x86 cefclient in C:\code\chromium\src
ninja: fatal: chdir to 'out/Release_GN_x86' - No such file or directory
ninja: Entering directory `out/Release_GN_x86'
x64 build failed with 1
At C:\code\cef_build.ps1:77 char:2
+     throw "x64 build failed with $($px64.ExitCode)";
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   g) [], RuntimeException
    + CategoryInfo          : OperationStopped: (x64 build failed with 1:Strin
    + FullyQualifiedErrorId : x64 build failed with 1


The command 'powershell -Command $ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue'; c:/code/cef_
build.ps1' returned a non-zero code: 1
Caught an exception: Process docker build --memory=30g --build-arg CEF_SAVE_SOURCES="0" --build-arg BINARY_EXT="zip" --b
uild-arg DUAL_BUILD="0" --build-arg GN_DEFINES="is_official_build=true proprietary_codecs=true ffmpeg_branding=Chrome" -
-build-arg GYP_DEFINES="" --build-arg CHROME_BRANCH="3396" -f Dockerfile_cef -t cef . exited with non zero code: 1 abort
ing!
        Exception Type: System.Management.Automation.RuntimeException
        Stack Trace: at RunProc, C:\build-cefsharp\functions.ps1: line 82
        at <ScriptBlock>, C:\build-cefsharp\build.ps1: line 70
        at <ScriptBlock>, <No file>: line 1
```

I might need to try to put `3770` to try to repro the origin build you had.

**Comment by mitchcapper** [comment]
Ah that is my mistake in your versions.ps1 put `$VAR_CHROME_BRANCH="3770";`
I will try to get my update out this week as well.

**Comment by maxhora** [comment]
Cool! Thanks! Trying with with `3770` now

**Comment by mitchcapper** [comment]
All set.
